networks:
  default: polygon-main-fork
compiler:
  solc:
    version: 0.6.6
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.1.0"
dependencies:
  - maticnetwork/pos-portal@1.5.2
  - OpenZeppelin/openzeppelin-contracts@3.1.0
